version: "3.3"
services:
  db:
    container_name: postgressss
    image: postgres:latest
    restart: always
    ports:
        - 5432:5432
    volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        # - data:/var/lib/postgresql/data
    environment:
        POSTGRES_PASSWORD: password
        POSTGRES_USER: postgres
        POSTGRES_DB: books

  bookapi:
    image: colapes/golang_book_api:latest
    restart: always
    environment:
        - DB_URL=postgres://postgres:password@postgressss:5432/books?sslmode=disable
        # - DB_URL=user=postgres dbname=books password=password sslmode=disable host=postgres port=5432
    ports:
      - 3585:3585
